name: Deploy React + Express to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and build React app
        run: |
          npm ci
          npm run build

      - name: Replace old build in react-eb-final
        run: |
          rm -rf react-eb-final/build
          cp -r build react-eb-final/

      - name: Zip the react-eb-final folder (includes .platform)
        run: |
          rm -f react-eb-final.zip
          cd react-eb-final
          zip -r ../react-eb-final.zip ./*
          cd ..

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: TodoApplication-frontend-env
          environment_name: TodoApplication-frontend-env-env
          region: ap-northeast-2
          version_label: react-eb-final-${{ github.run_number }}
          deployment_package: react-eb-final.zip
